version: "3"
services:
  backend:
    build: ./server
    environment:
      - PORT=3000
      - NODE_ENV=dev
      - DATABASE=GT
      - DB_USER=bader
      - password=2001
      - host=postgres
    ports:
      - 3000:3000
    volumes:
      - ./server:/server/
    depends_on:
      - keycloak
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bader
      POSTGRES_PASSWORD: 2001
      POSTGRES_DB: GT
    container_name: postgres
  adminer:
    image: adminer
    ports:
      - 7000:8080
    container_name: adminer
  frontend:
    build: ./client
    ports:
      - 2900:2900
    volumes:
      - ./client:/client/

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=GT
      - DB_USER=bader
      - DB_PASSWORD=2001
    ports:
      - 8080:8080
    depends_on:
      - postgres
    container_name: keycloak
