version: "3"
services:
  app:
    build: .
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      - PORT=9090
      - NODE_ENV=development
      - DATABASE=GT
      - DB_USER=postgres
      - password=2001
      - host=localhost
