version: "3"
services:
  backend:
    build: ./server
    environment:
      - PORT=5050
      - NODE_ENV=dev
      - DATABASE=GT
      - DB_USER=bader
      - password=2001
      - host=localhost
    ports:
      - 5050:5050
    volumes:
      - ./server:/server/
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bader
      POSTGRES_PASSWORD: 2001
      POSTGRES_DB: GT
    container_name: postgres
  adminer:
    image: adminer
    ports:
      - 7000:8080
    container_name: adminer
  frontend:
    build:
      ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/client/
  