# Use the official Node.js image as the base image
FROM node:12

# Set the working directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port the application will run on
EXPOSE 9090

# Set the environment variable for the Node environment
ENV NODE_ENV development

# Define the command to run the application
CMD [ "npm run", "start:$NODE_ENV" ]
